	PROGRAM TEST
	USE DFPORT
	PARAMETER DIM=1000,NUMAR=10,DIM1=DIM+1
	REAL(4) VAL(2)
	REAL(4) TARRAY(2)
	DOUBLE PRECISION MAT(DIM,DIM1),X(DIM)
	DOUBLE PRECISION TEMP
	DOUBLE PRECISION REZ(DIM)
	integer(4) ra
	ra=0
	DO I=1,DIM
		REZ(I)=I
	END DO
	DO L=1,NUMAR
		DO I=1,DIM
			DO J=1,DIM
				MAT(I,J)=DRAND(RA)
			END DO
			TEMP=0.0
			DO J=1,DIM
				IF(J .NE. I) THEN
					TEMP=TEMP+ABS(MAT(I,J))
				END IF
			END DO
			MAT(I,I)=TEMP+MAT(I,I)
		END DO
		DO I=1,DIM
			MAT(I,DIM1)=0.0
			DO J=1,DIM
				MAT(I,DIM1)=MAT(I,DIM1)+MAT(I,J)*REZ(J)
			END DO
		END DO
		VAL(1)=DTIME(TARRAY)
		CALL GAUSS_JORDAN(MAT,REZ,X)
		VAL(2)=DTIME(TARRAY)
		PRINT *,TARRAY(1),"AND",TARRAY(2),"OR",VAL(2)
		DO I=1,DIM
			IF (ABS(REZ(I)-X(I)) .GE. 1E-4) THEN
				PRINT *,REZ(I),'=',X(I)
			END IF
		END DO
	END DO
	END
	SUBROUTINE GAUSS_JORDAN(MAT,REZ,X)
	PARAMETER DIM=1000,DIM1=DIM+1
	DOUBLE PRECISION MAT(DIM,DIM1),X(DIM)
	DOUBLE PRECISION TEMP
	DOUBLE PRECISION REZ(DIM)
	DO K=1,DIM
		DO I=K+1,DIM
			TEMP=MAT(I,K)/MAT(K,K)
			DO J=K+1,DIM
				MAT(I,J)=MAT(I,J)-TEMP*MAT(K,J)
			END DO
			MAT(I,DIM1)=MAT(I,DIM1)-TEMP*MAT(K,DIM1)
		END DO
		DO I=1,K-1
			TEMP=MAT(I,K)/MAT(K,K)
			DO J=K+1,DIM
				MAT(I,J)=MAT(I,J)-TEMP*MAT(K,J)
			END DO
			MAT(I,DIM1)=MAT(I,DIM1)-TEMP*MAT(K,DIM1)
		END DO
	END DO
	DO I=1,DIM
		X(I)=MAT(I,DIM1)/MAT(I,I)
	END DO
	END SUBROUTINE GAUSS_JORDAN