	PROGRAM TEST
	USE DFPORT
	PARAMETER DIM=300,NUMAR=10,DIM1=DIM+1
	REAL(4) VAL(2)
	REAL(4) TARRAY(2)
	DOUBLE PRECISION MAT(DIM,DIM1),X(DIM)
	DOUBLE PRECISION TEMP
	DOUBLE PRECISION REZ(DIM)
	INTEGER (4) RA
	DO I=1,DIM
		REZ(I)=I
	END DO
	RA=0
	DO L=1,NUMAR
		DO I=1,DIM
			DO J=1,DIM
				MAT(I,J)=DRAND(RA)
			END DO
			TEMP=0.0
			DO J=1,DIM
				IF(J .NE. I) THEN
					TEMP=TEMP+ABS(MAT(I,J))
				END IF
			END DO
			MAT(I,I)=TEMP+MAT(I,I)
		END DO
		DO I=1,DIM
			MAT(I,DIM1)=0.0
			DO J=1,DIM
				MAT(I,DIM1)=MAT(I,DIM1)+MAT(I,J)*REZ(J)
			END DO
		END DO
		VAL(1)=DTIME(TARRAY)
		CALL GAUSS(MAT,REZ,X)
		VAL(2)=DTIME(TARRAY)
		PRINT *,TARRAY(1),"AND",TARRAY(2),"OR",VAL(2)
		DO I=1,DIM
			IF(ABS(REZ(I)-X(I)) .GE. 1E-4) THEN
				PRINT *,REZ(I),'=',X(I)
			END IF
		END DO
	END DO
	END
	SUBROUTINE GAUSS(MAT,REZ,X)
	PARAMETER DIM=300,DIM1=DIM+1
	DOUBLE PRECISION MAT(DIM,DIM1)
	DOUBLE PRECISION X(DIM)
	DOUBLE PRECISION TEMP
	DOUBLE PRECISION REZ(DIM)
		DO K=1,DIM-1
			DO I=K+1,DIM
				TEMP=MAT(I,K)/MAT(K,K)
				DO J=K+1,DIM
					MAT(I,J)=MAT(I,J)-TEMP*MAT(K,J)
				END DO
				MAT(I,DIM1)=MAT(I,DIM1)-TEMP*MAT(K,DIM1)
			END DO
		END DO
		DO I=DIM,1,-1
			TEMP=0.0
			X(I)=0.0
			DO J=I+1,DIM
				TEMP=TEMP+MAT(I,J)*X(J)
			END DO
			X(I)=(MAT(I,DIM1)-TEMP)/MAT(I,I)
		END DO
	END SUBROUTINE GAUSS