# Generated by makegen....

TARGET =gj-upc
OBJECTS =bench-upc.o

CC = upc
CFLAGS =-O3 $(INCDIR) -Wall

LIBS =
LIBDIR =
INCDIR = -I/usr/include -I./

INSTALLDIR = 

all: clean 	$(OBJECTS)
	$(CC) $(CFLAGS) -o $(TARGET)  $(OBJECTS)

clean:
	rm -f a.out core *~ \#* *.bak $(TARGET) *.o

