!	PROGRAM PENTRU INTEGRALA PRIN METODA DREPTUNGHIULUI LA STINGA MAPLE=leftsum
	PROGRAM DREPTUNGHI
	DOUBLE PRECISION INTEGRALE
	INTEGER(4) N
	DOUBLE PRECISION H,LS,LD
	INTEGRALE=0.0
	READ *,LS,LD,N
	H=(LD-LS)/N
	DO I=0,N-1
		INTEGRALE=INTEGRALE+H*FUNC(LS+I*H)
	END DO
	PRINT *,'VALOAREA INTEGRALEI ESTE',INTEGRALE
	END
	DOUBLE PRECISION FUNCTION FUNC(X)
		DOUBLE PRECISION X
		FUNC=SIN(X)
		RETURN
	END FUNCTION FUNC
	