! Program pentru calculul integralei cu metoda trapezului
	PROGRAM TRAPEZ
	DOUBLE PRECISION LS,LD,H,INTEGRALE
	INTEGER(4) N
	READ *,LS,LD,N
	H=(LD-LS)/N
	INTEGRALE=H*(CALCUL(LS)+CALCUL(LD))/2
	DO I=1,N-1
		INTEGRALE=INTEGRALE+H*CALCUL(LS+I*H)
	END DO
	PRINT *,'INTEGRALA ESTE ',INTEGRALE
	END
	